### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by chiang-yuan** [chiang-yuan/llamp#3]
Move TODOs here to keep track on the essential and extended functionalities 

🔥 : Urgent
🎯 : Top priority
👍🏻 : Good to work on
🍵 : Please chill and do it for fun

# Core Functionalities

- [x] Convert Materials Project API response to natural language output 
- [x] Instead of using prompt template, use langchain tool to read API specs and generate compatible input fields. Caveat: Materials Project's API specs may not be very comprehensive #23 
- [ ] 🍵 [Whisper](https://openai.com/research/whisper) interface for human voice input and output 
- [x] Extract academic papers from arXiv and generate response to user's questions. Refer to [openai-cookbook example](https://github.com/openai/openai-cookbook/blob/5783656852d507c335955d14875ebc9902f628ef/examples/How_to_call_functions_for_knowledge_retrieval.ipynb)
- [x] Web app integration with [Elementari](https://github.com/janosh/elementari) to visualize queried material structure!!! #24 
- [x] 🔥 Losing response history in frontend #32 
- [ ] 🔥 Large request and error handing #31 
- [ ] 🔥 User key conflicts
- [x] 🎯 Input field for Materials Project API key
- [x] 🎯 Authorship and Introduction page (one page together)
- [x] 🎯 Clear chat history button
- [x] 🎯 Responsive pages #34
- [x] 🎯 Annotate structure with `material_id`
- [x] 🎯 Markdown interpreter for messages
- [x] 🎯  Create hyperlink whenever `material_id` (such as `mp-12345`) or crystal structure shows up to forward users to MP website #29
- [x] #42
- [x] #43
- [ ] #40
- [ ] #39
- [ ] #38
- [x] 👍🏻 Dark/Light mode switch using Skeleton inherent css class 
- [ ] 👍🏻 Improve crystal structure visualization (bond, graph, etc) janosh/elementari
- [ ] 👍🏻 User identification, login, and statistic collection 
- [ ] 👍🏻 Refine tool description
- [x] #37
- [ ] 👍🏻 Clean up unused code

# Extended Functionality

- [ ] Wikipedia/Wolfram alpha integration for general information (for example, melting points)
- [x] Automated DFT calculations using MP workflows (pymatgen, atomate2, fireworks, ... etc)
